export const SEED_TRANSACTIONS = [
  {
    id: "seed-1",
    title: "Freelance UI Project",
    amount: 8500,
    type: "income",
    category: "Income",
    date: "2026-08-28",
    description: "Final payout for a client dashboard redesign.",
  },
  {
    id: "seed-2",
    title: "Grocery Run",
    amount: 1250,
    type: "expense",
    category: "Food",
    date: "2026-08-27",
    description: "Weekly groceries and household basics.",
  },
  {
    id: "seed-3",
    title: "Monthly Allowance",
    amount: 6000,
    type: "income",
    category: "Income",
    date: "2026-08-25",
    description: "Support from family for the month.",
  },
  {
    id: "seed-4",
    title: "Grab to Campus",
    amount: 210,
    type: "expense",
    category: "Transportation",
    date: "2026-08-24",
    description: "",
  },
  {
    id: "seed-5",
    title: "Streaming Subscription",
    amount: 149,
    type: "expense",
    category: "Entertainment",
    date: "2026-08-22",
    description: "Monthly plan.",
  },
  {
    id: "seed-6",
    title: "Electricity Bill",
    amount: 1840,
    type: "expense",
    category: "Bills",
    date: "2026-08-20",
    description: "Shared apartment utility split.",
  },
  {
    id: "seed-7",
    title: "New Sneakers",
    amount: 3200,
    type: "expense",
    category: "Shopping",
    date: "2026-08-18",
    description: "",
  },
  {
    id: "seed-8",
    title: "Design Course",
    amount: 990,
    type: "expense",
    category: "Education",
    date: "2026-08-15",
    description: "UI motion design mini-course.",
  },
  {
    id: "seed-9",
    title: "Clinic Visit",
    amount: 650,
    type: "expense",
    category: "Health",
    date: "2026-08-12",
    description: "",
  },
  {
    id: "seed-10",
    title: "Side Gig Payout",
    amount: 2400,
    type: "income",
    category: "Income",
    date: "2026-08-10",
    description: "Logo + branding package.",
  },
];
